//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type2/STType2Tag.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/st/st25sdk/RFReaderInterface.h"
#include "com/st/st25sdk/type2/STType2Tag.h"
#include "com/st/st25sdk/type2/Type2Tag.h"

#pragma clang diagnostic ignored "-Wprotocol"

@implementation ComStSt25sdkType2STType2Tag

- (instancetype)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface {
  ComStSt25sdkType2STType2Tag_initWithComStSt25sdkRFReaderInterface_(self, readerInterface);
  return self;
}

- (instancetype)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                        withByteArray:(IOSByteArray *)uid {
  ComStSt25sdkType2STType2Tag_initWithComStSt25sdkRFReaderInterface_withByteArray_(self, readerInterface, uid);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, 1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, 1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComStSt25sdkRFReaderInterface:);
  methods[1].selector = @selector(initWithComStSt25sdkRFReaderInterface:withByteArray:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComStSt25sdkRFReaderInterface;", "LComStSt25sdkSTException;", "LComStSt25sdkRFReaderInterface;[B" };
  static const J2ObjcClassInfo _ComStSt25sdkType2STType2Tag = { "STType2Tag", "com.st.st25sdk.type2", ptrTable, methods, NULL, 7, 0x401, 2, 0, -1, -1, -1, -1, -1 };
  return &_ComStSt25sdkType2STType2Tag;
}

@end

void ComStSt25sdkType2STType2Tag_initWithComStSt25sdkRFReaderInterface_(ComStSt25sdkType2STType2Tag *self, id<ComStSt25sdkRFReaderInterface> readerInterface) {
  ComStSt25sdkType2Type2Tag_initWithComStSt25sdkRFReaderInterface_(self, readerInterface);
}

void ComStSt25sdkType2STType2Tag_initWithComStSt25sdkRFReaderInterface_withByteArray_(ComStSt25sdkType2STType2Tag *self, id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid) {
  ComStSt25sdkType2Type2Tag_initWithComStSt25sdkRFReaderInterface_withByteArray_(self, readerInterface, uid);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComStSt25sdkType2STType2Tag)
