//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/ST25DVTransferTask.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25nfcType5St25dvST25DVTransferTask")
#ifdef RESTRICT_ComStSt25nfcType5St25dvST25DVTransferTask
#define INCLUDE_ALL_ComStSt25nfcType5St25dvST25DVTransferTask 0
#else
#define INCLUDE_ALL_ComStSt25nfcType5St25dvST25DVTransferTask 1
#endif
#undef RESTRICT_ComStSt25nfcType5St25dvST25DVTransferTask

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25nfcType5St25dvST25DVTransferTask_) && (INCLUDE_ALL_ComStSt25nfcType5St25dvST25DVTransferTask || defined(INCLUDE_ComStSt25nfcType5St25dvST25DVTransferTask))
#define ComStSt25nfcType5St25dvST25DVTransferTask_

#define RESTRICT_JavaLangRunnable 1
#define INCLUDE_JavaLangRunnable 1
#include "java/lang/Runnable.h"

@class ComStSt25sdkType5St25dvST25DVCTag;
@class ComStSt25sdkType5St25dvST25DVTag;
@class IOSByteArray;
@protocol ComStSt25nfcType5St25dvST25DVTransferTask_OnTransferListener;

@interface ComStSt25nfcType5St25dvST25DVTransferTask : NSObject < JavaLangRunnable > {
 @public
  ComStSt25sdkType5St25dvST25DVTag *mST25DVTag_;
  ComStSt25sdkType5St25dvST25DVCTag *mST25DVCTag_;
}
@property (readonly, class) jint FAST_BASIC_TRANSFER_FUNCTION NS_SWIFT_NAME(FAST_BASIC_TRANSFER_FUNCTION);
@property (readonly, class) jint FAST_IMAGE_UPLOAD_FUNCTION NS_SWIFT_NAME(FAST_IMAGE_UPLOAD_FUNCTION);
@property (readonly, class) jint FAST_IMAGE_DOWNLOAD_FUNCTION NS_SWIFT_NAME(FAST_IMAGE_DOWNLOAD_FUNCTION);
@property (readonly, class) jint FAST_FIRMWARE_UPDATE_FUNCTION NS_SWIFT_NAME(FAST_FIRMWARE_UPDATE_FUNCTION);
@property (readonly, class) jint FAST_PRESENT_PWD_FUNCTION NS_SWIFT_NAME(FAST_PRESENT_PWD_FUNCTION);
@property (readonly, class) jint FAST_RANDOM_TRANSFER_FUNCTION NS_SWIFT_NAME(FAST_RANDOM_TRANSFER_FUNCTION);
@property (readonly, class) jint FAST_CHRONO_DEMO_FUNCTION NS_SWIFT_NAME(FAST_CHRONO_DEMO_FUNCTION);

+ (jint)FAST_BASIC_TRANSFER_FUNCTION;

+ (jint)FAST_IMAGE_UPLOAD_FUNCTION;

+ (jint)FAST_IMAGE_DOWNLOAD_FUNCTION;

+ (jint)FAST_FIRMWARE_UPDATE_FUNCTION;

+ (jint)FAST_PRESENT_PWD_FUNCTION;

+ (jint)FAST_RANDOM_TRANSFER_FUNCTION;

+ (jint)FAST_CHRONO_DEMO_FUNCTION;

#pragma mark Public

- (instancetype __nonnull)initWithInt:(jint)action
                        withByteArray:(IOSByteArray *)buffer
withComStSt25sdkType5St25dvST25DVCTag:(ComStSt25sdkType5St25dvST25DVCTag *)tag;

- (instancetype __nonnull)initWithInt:(jint)action
                        withByteArray:(IOSByteArray *)buffer
 withComStSt25sdkType5St25dvST25DVTag:(ComStSt25sdkType5St25dvST25DVTag *)tag;

- (void)pause;

- (jint)prepare;

- (void)resume;

- (void)run;

- (void)setST25DVTagWithComStSt25sdkType5St25dvST25DVCTag:(ComStSt25sdkType5St25dvST25DVCTag *)tag;

- (void)setST25DVTagWithComStSt25sdkType5St25dvST25DVTag:(ComStSt25sdkType5St25dvST25DVTag *)tag;

- (void)setTransferListenerWithComStSt25nfcType5St25dvST25DVTransferTask_OnTransferListener:(id<ComStSt25nfcType5St25dvST25DVTransferTask_OnTransferListener>)listener;

- (void)start;

- (void)stop;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25nfcType5St25dvST25DVTransferTask)

J2OBJC_FIELD_SETTER(ComStSt25nfcType5St25dvST25DVTransferTask, mST25DVTag_, ComStSt25sdkType5St25dvST25DVTag *)
J2OBJC_FIELD_SETTER(ComStSt25nfcType5St25dvST25DVTransferTask, mST25DVCTag_, ComStSt25sdkType5St25dvST25DVCTag *)

inline jint ComStSt25nfcType5St25dvST25DVTransferTask_get_FAST_BASIC_TRANSFER_FUNCTION(void);
#define ComStSt25nfcType5St25dvST25DVTransferTask_FAST_BASIC_TRANSFER_FUNCTION 3
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25nfcType5St25dvST25DVTransferTask, FAST_BASIC_TRANSFER_FUNCTION, jint)

inline jint ComStSt25nfcType5St25dvST25DVTransferTask_get_FAST_IMAGE_UPLOAD_FUNCTION(void);
#define ComStSt25nfcType5St25dvST25DVTransferTask_FAST_IMAGE_UPLOAD_FUNCTION 9
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25nfcType5St25dvST25DVTransferTask, FAST_IMAGE_UPLOAD_FUNCTION, jint)

inline jint ComStSt25nfcType5St25dvST25DVTransferTask_get_FAST_IMAGE_DOWNLOAD_FUNCTION(void);
#define ComStSt25nfcType5St25dvST25DVTransferTask_FAST_IMAGE_DOWNLOAD_FUNCTION 7
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25nfcType5St25dvST25DVTransferTask, FAST_IMAGE_DOWNLOAD_FUNCTION, jint)

inline jint ComStSt25nfcType5St25dvST25DVTransferTask_get_FAST_FIRMWARE_UPDATE_FUNCTION(void);
#define ComStSt25nfcType5St25dvST25DVTransferTask_FAST_FIRMWARE_UPDATE_FUNCTION 4
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25nfcType5St25dvST25DVTransferTask, FAST_FIRMWARE_UPDATE_FUNCTION, jint)

inline jint ComStSt25nfcType5St25dvST25DVTransferTask_get_FAST_PRESENT_PWD_FUNCTION(void);
#define ComStSt25nfcType5St25dvST25DVTransferTask_FAST_PRESENT_PWD_FUNCTION 8
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25nfcType5St25dvST25DVTransferTask, FAST_PRESENT_PWD_FUNCTION, jint)

inline jint ComStSt25nfcType5St25dvST25DVTransferTask_get_FAST_RANDOM_TRANSFER_FUNCTION(void);
#define ComStSt25nfcType5St25dvST25DVTransferTask_FAST_RANDOM_TRANSFER_FUNCTION 10
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25nfcType5St25dvST25DVTransferTask, FAST_RANDOM_TRANSFER_FUNCTION, jint)

inline jint ComStSt25nfcType5St25dvST25DVTransferTask_get_FAST_CHRONO_DEMO_FUNCTION(void);
#define ComStSt25nfcType5St25dvST25DVTransferTask_FAST_CHRONO_DEMO_FUNCTION 11
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25nfcType5St25dvST25DVTransferTask, FAST_CHRONO_DEMO_FUNCTION, jint)

FOUNDATION_EXPORT void ComStSt25nfcType5St25dvST25DVTransferTask_initWithInt_withByteArray_withComStSt25sdkType5St25dvST25DVTag_(ComStSt25nfcType5St25dvST25DVTransferTask *self, jint action, IOSByteArray *buffer, ComStSt25sdkType5St25dvST25DVTag *tag);

FOUNDATION_EXPORT ComStSt25nfcType5St25dvST25DVTransferTask *new_ComStSt25nfcType5St25dvST25DVTransferTask_initWithInt_withByteArray_withComStSt25sdkType5St25dvST25DVTag_(jint action, IOSByteArray *buffer, ComStSt25sdkType5St25dvST25DVTag *tag) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25nfcType5St25dvST25DVTransferTask *create_ComStSt25nfcType5St25dvST25DVTransferTask_initWithInt_withByteArray_withComStSt25sdkType5St25dvST25DVTag_(jint action, IOSByteArray *buffer, ComStSt25sdkType5St25dvST25DVTag *tag);

FOUNDATION_EXPORT void ComStSt25nfcType5St25dvST25DVTransferTask_initWithInt_withByteArray_withComStSt25sdkType5St25dvST25DVCTag_(ComStSt25nfcType5St25dvST25DVTransferTask *self, jint action, IOSByteArray *buffer, ComStSt25sdkType5St25dvST25DVCTag *tag);

FOUNDATION_EXPORT ComStSt25nfcType5St25dvST25DVTransferTask *new_ComStSt25nfcType5St25dvST25DVTransferTask_initWithInt_withByteArray_withComStSt25sdkType5St25dvST25DVCTag_(jint action, IOSByteArray *buffer, ComStSt25sdkType5St25dvST25DVCTag *tag) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25nfcType5St25dvST25DVTransferTask *create_ComStSt25nfcType5St25dvST25DVTransferTask_initWithInt_withByteArray_withComStSt25sdkType5St25dvST25DVCTag_(jint action, IOSByteArray *buffer, ComStSt25sdkType5St25dvST25DVCTag *tag);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25nfcType5St25dvST25DVTransferTask)

#endif

#if !defined (ComStSt25nfcType5St25dvST25DVTransferTask_OnTransferListener_) && (INCLUDE_ALL_ComStSt25nfcType5St25dvST25DVTransferTask || defined(INCLUDE_ComStSt25nfcType5St25dvST25DVTransferTask_OnTransferListener))
#define ComStSt25nfcType5St25dvST25DVTransferTask_OnTransferListener_

@class IOSByteArray;

@protocol ComStSt25nfcType5St25dvST25DVTransferTask_OnTransferListener < JavaObject >

- (void)transferOnProgressWithDouble:(jdouble)progressStatus;

- (void)transferFinishedWithBoolean:(jboolean)success
                           withLong:(jlong)time
                      withByteArray:(IOSByteArray *)buffer;

- (IOSByteArray *)getDataToWrite;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25nfcType5St25dvST25DVTransferTask_OnTransferListener)

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25nfcType5St25dvST25DVTransferTask_OnTransferListener)

#endif

#if !defined (ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_) && (INCLUDE_ALL_ComStSt25nfcType5St25dvST25DVTransferTask || defined(INCLUDE_ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent))
#define ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_Enum) {
  ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_Enum_START = 0,
  ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_Enum_STOP = 1,
  ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_Enum_PAUSE = 2,
  ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_Enum_RESUME = 3,
};

@interface ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent : JavaLangEnum

@property (readonly, class, nonnull) ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent *START NS_SWIFT_NAME(START);
@property (readonly, class, nonnull) ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent *STOP NS_SWIFT_NAME(STOP);
@property (readonly, class, nonnull) ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent *PAUSE NS_SWIFT_NAME(PAUSE);
@property (readonly, class, nonnull) ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent *RESUME NS_SWIFT_NAME(RESUME);
+ (ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent * __nonnull)START;

+ (ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent * __nonnull)STOP;

+ (ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent * __nonnull)PAUSE;

+ (ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent * __nonnull)RESUME;

#pragma mark Public

+ (ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent *ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_values_[];

inline ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent *ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_get_START(void);
J2OBJC_ENUM_CONSTANT(ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent, START)

inline ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent *ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_get_STOP(void);
J2OBJC_ENUM_CONSTANT(ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent, STOP)

inline ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent *ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_get_PAUSE(void);
J2OBJC_ENUM_CONSTANT(ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent, PAUSE)

inline ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent *ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_get_RESUME(void);
J2OBJC_ENUM_CONSTANT(ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent, RESUME)

FOUNDATION_EXPORT IOSObjectArray *ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_values(void);

FOUNDATION_EXPORT ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent *ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent *ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25nfcType5St25dvST25DVTransferTask_ST25DVTransferEvent)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25nfcType5St25dvST25DVTransferTask")
